#!/usr/bin/env zsh

# Path to your oh-my-zsh installation.
export ZSH=/usr/local/share/zsh/oh-my-zsh
export ZSH_SHARE=/usr/local/share/workspace/share/zsh

# Shell Helpers 
source /usr/local/config/zsh/helpers.sh

# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="muse"

# Use hyphen-insensitive completion.
HYPHEN_INSENSITIVE="true"

# Disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Stop changing the window title
DISABLE_AUTO_TITLE="true"

# Insecure completion-dependent directories detected
ZSH_DISABLE_COMPFIX="true"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git gitignore sudo rsync)

# Load Oh my ZSH!
source $ZSH/oh-my-zsh.sh

# Path
export PATH="$HOME/bin:/usr/local/share/composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Editor
export EDITOR=nvim
export VISUAL=nvim
alias vim=nvim
alias vi=nvim

# Tmux
export TMUX_PLUGIN_MANAGER_PATH="/usr/local/share/tmux/plugins/"

# Customize FZF
source $ZSH_SHARE/fzf.sh

# Ctrl-n nnn
source $ZSH_SHARE/nnn.sh

# Secure Shellfish integration
source $ZSH_SHARE/shellfish.sh

autoload -Uz bashcompinit && bashcompinit
source /root/bens/swarm/lib/completion.sh

# Misc
alias server="python -m SimpleHTTPServer"
